### ISSUE TITLE
Add *args and **kwargs

### ISSUE THREAD

**Issue by phrdang** [code-for-tomorrow/python#136]
## New Topic Request

Add an explanation of `*args, **kwargs` either in Intermediate Ch. 11 Functions > 11.2 Parameters. There should be example code and practice problems as well.

## Why it's needed

This is a feature of Python that is used pretty widely and isn't terribly hard to understand, so it's a good add to the curriculum.

**Comment by BenVN123** [comment]
Added to Notion. Note that I changed the "Parameter" section to 11.3 since I thought that it was a better order and less confusing.
