### ISSUE TITLE
Ch. 16 Quiz Questions Unclear

### ISSUE THREAD

**Issue by phrdang** [code-for-tomorrow/python#76]
## Describe the issue

Questions 3 and 4 of the Ch. 16 Quiz are unclear. 

Q3: Students may think that answer D is correct (instead of C) because `min_index` changes on line 6 of the example code in Section 16.3, which is under the inner for loop and if the if statement is true.

Q4: Insertion sort should not be a quiz question since it isn't taught and the given explanation isn't easy to understand.

- Chapter: 16
- Section: Chapter 16 Quiz

## Screenshot

<img width="646" alt="Screen Shot 2021-03-10 at 11 44 40 AM" src="https://user-images.githubusercontent.com/35876322/110688034-02623480-8196-11eb-8e74-34d9ef31f0ff.png">

**Comment by chrehall68** [comment]
Fixed on notion quiz.
