### ISSUE TITLE
Selection sort described incorrectly

### ISSUE THREAD

**Issue by phrdang** [code-for-tomorrow/python#77]
## Describe the issue

Selection sort is described incorrectly.

- Chapter: 16
- Section: 16.2

## Expected behavior

The text should say that selection sort searches for the "smallest" or "least" element instead of "greatest" element (see screenshot below).

## Screenshots or Errors

<img width="646" alt="Screen Shot 2021-03-10 at 11 46 55 AM" src="https://user-images.githubusercontent.com/35876322/110688337-5240fb80-8196-11eb-9425-62caed7a1201.png">

**Comment by chrehall68** [comment]
Fixed on notion.
