### ISSUE TITLE
Ch. 17 Thinkific text issues

### ISSUE THREAD

**Issue by phrdang** [code-for-tomorrow/python#78]
## Describe the issue

- Chapter: 17
- Sections: 17.10, 17.13

**17.10:** 
- `print(x & y)` is said to be the same as the union of sets x and y, but actually it's the intersection of x and y.
- `print(x.union(y))` is said to print `{1, 2, 3, 4, 5, 3, 4, 5, 6, 7}` which is incorrect since a set can only contain unique elements. It should print `{1, 2, 3, 4, 5, 6, 7}` instead.

**17:13:**
- See screenshot - it should be clarified that inserting/removing from the front of a **list** is O(n) (it's ambiguous right now).

## Screenshots or Errors

From 17.13:

<img width="615" alt="Screen Shot 2021-03-10 at 4 34 21 PM" src="https://user-images.githubusercontent.com/35876322/110717747-7adceb80-81be-11eb-9b08-87c25aab8f79.png">

**Comment by chrehall68** [comment]
Fixed on notion.
