### ISSUE TITLE
Add section on infinite recursion and iterative fibonacci in Ch. 18

### ISSUE THREAD

**Issue by phrdang** [code-for-tomorrow/python#79]
## New Topic Request

Add a section **about infinite recursion** in Ch. 18 Recursion. Include:

- What infinite recursion is and why it's caused
- An example of a function that is infinitely recursive
- The error message that Python gives (`RecursionError`)

Add a section about **iterative fibonacci**. Include:

- Why recursive fib is inefficient
- How to implement fibonacci iteratively (or make it a practice exercise)

## Why it's needed

**Infinite Recursion**

When people first start learning recursion, they may forget to add base cases. Pointing out infinitely recursive functions will make people remember to include base cases the same way an infinite loop might make a programmer more aware of what their loop's condition is.

**Iterative Fibonacci**

Illustrates that recursive algorithms can be rewritten as iterative ones, which are sometimes more efficient

**Comment by BenVN123** [comment]
Added infinite recursion and iterative Fibonacci sections on Notion.
