### ISSUE TITLE
Add "else" and "assert" to exception handling chapter 19

### ISSUE THREAD

**Issue by phrdang** [code-for-tomorrow/python#82]
## New Topic Request

1. Include an explanation of the purpose of an `else` clause in a `try`-`except` block.
2. Include an explanation of the `assert` keyword and how it is used with a `try` - `except` block.

- Chapter: 19
- Section: Before the "Finally" section

## Why it's needed

1. Sometimes programmers need to write out what should happen if no errors/exceptions are raised. This is the purpose of an `else` clause during exception handling and students should learn about it in addition to the `finally` clause.
2. `AssertionError` is mentioned in Ch. 19 but it's never explained how you can "assert" something in the code.

**Comment by BenVN123** [comment]
Added "else" and "assert" section (19.4) to Notion.
