### ISSUE TITLE
Issues in Ch. 19 practice problems

### ISSUE THREAD

**Issue by phrdang** [code-for-tomorrow/python#84]
## Describe the issue

- Chapter: 19
- Section: 19.3
- Problem Title: Type Checker

This problem's instructions need to be clarified to state that the `type_checker` function prints the result of `x * 4` instead of returning it. Another issue is that the solution to this problem has a logic error. The `try-except` only handles `TypeError`s, but no `TypeError`s are thrown because it is possible in Python to multiply an integer by a string. For example:

```python
print("hi" * 3)
```

Results in:

```
hihihi
```

Instead, the `try-except` should catch a `ValueError` since `x` should be converted into a `float` with the `float` function and *then* multiply that by 4.

- Chapter: 19
- Section: 19.5
- Problem Title: Finally Use

The file that you can download from Thinkific is apparently the solution code (according to one of my students). Instead, it should be the practice template file.

**Comment by chrehall68** [comment]
Fixed bug in latest pull request ("Fix * bug").
