### ISSUE TITLE
Add more json methods to Ch. 20

### ISSUE THREAD

**Issue by phrdang** [code-for-tomorrow/python#86]
## New Topic Request

Add explanations of the `dumps` and `loads` method from the `json` module.

Chapter: 20
Section: 20.6 Json (JSON should also be in all caps.)

## Why it's needed

`dumps` and `loads` are useful methods that students might as well learn alongside `dump` and `load`. Also it minimizes confusion later on when they might encounter the methods.

**Comment by BenVN123** [comment]
Added to Notion.
