### ISSUE TITLE
Miscellaneous Ch. 20 File I/O issues

### ISSUE THREAD

**Issue by phrdang** [code-for-tomorrow/python#87]
## Describe the issue

All of the following issues are found in **20.6 JSON**:

- There are no practice problem instructions on Thinkific (they're only on the template code on GitHub)
- For JSON Practice 1, the instructions are a bit ambiguous when it tells students to add `names` to the top dictionary. Instead, it should specify that `"names"` should be the key and the `names` list should be the corresponding value.
- Throughout the JSON section, I think it would also be useful to just call the "top dictionary" the "dictionary" because it's a bit confusing why it's even called "top dictionary"

**Ch. 20 Quiz Typo**

- Question 5 should say "Which of the following correctly demonstrates how to use the json **module** to write to a .json file and then read from it?"

**Comment by BenVN123** [comment]
Fixed on Notion.
