### ISSUE TITLE
Add more text file reading and writing methods to Ch. 20

### ISSUE THREAD

**Issue by phrdang** [code-for-tomorrow/python#88]
## New Topic Request

Add all of the methods from this resource: https://www.programiz.com/python-programming/file-operation **EXCEPT**:

- `detach`
- `fileno`
- `flush`
- `isatty`
- `truncate`

because they're not as commonly used for text file I/O compared to the other methods. This would all go under 20.2 Text Files, although I wouldn't be surprised if curriculum developers would need to separate it into 2 sections (Reading Text Files, Writing Text Files).

## Why it's needed

The `read` and `write` methods are relatively limited. To give students more flexibility in file I/O (which also opens the door for more rigorous file I/O exercises), they should learn the other methods.

**Comment by BenVN123** [comment]
Added on Notion, section 20.2
