### ISSUE TITLE
Clarify List Practice instructions with demo video

### ISSUE THREAD

**Issue by phrdang** [code-for-tomorrow/python#89]
## Describe the issue

Please clarify the practice problem instructions by providing example output or a demo video so that students know the exact requirements of the program.

- Chapter: 19
- Section: 19.6
- Problem Title: List Practice

**Comment by BenVN123** [comment]
I made a demo video. Where should I put it?

**Comment by BenVN123** [comment]
It has been posted.
[https://www.youtube.com/watch?v=yUxvJm1ylnk&list=PLaxib7_MDmWcqmEknhne6JYg7Wg06qmmD&index=9](https://www.youtube.com/watch?v=yUxvJm1ylnk&list=PLaxib7_MDmWcqmEknhne6JYg7Wg06qmmD&index=9)
